site_name: dribdat docs
site_url: https://docs.dribdat.cc/
nav:
    - About: about.md
    - Usage: usage.md
    - Installation: deploy.md
    - Contribute: contribute.md
    - Whitepaper: whitepaper.md
    - Help: trouble.md
theme:
    name: bootstrap4
    next_previous: true
plugins:
    - bootstrap4-blockquotes
    - bootstrap4-tables
markdown_extensions:
  - toc:
      toc_depth: 2