site_name: dribdat.cc
site_url: https://dribdat.cc/
nav:
    - Usage: usage.md
    - Overview: about.md
    - Installation: deploy.md
    - Contribute: contribute.md
    - Whitepaper: whitepaper.md
    - Help: trouble.md
theme:
    name: bootstrap4
    next_previous: true
    titles_only: true
    extra_css: [extra.css]
plugins:
    - bootstrap4-blockquotes
    - bootstrap4-tables
markdown_extensions:
  - toc:
      toc_depth: 2
