[tool.poetry]
name = "dribdat-docs"
version = "0.1.0"
description = "A documentation site for dribdat"
authors = ["Oleg Lavrovsky <oleg@datalets.ch>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.7"
mkdocs = "^1.3.1"
mkdocs-theme-bootstrap4 = "^0.4.0"
livemark = "^0.109.0"
ghp-import = "^2.1.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
